# Generated by Django 4.2.7 on 2023-11-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Очивки', 'verbose_name_plural': 'Очивки'},
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Рекламное обьявление', 'verbose_name_plural': 'Рекламные обьявление'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметки', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль юзера', 'verbose_name_plural': 'Профиля юзеров'},
        ),
    ]
